In [1]:
import selections as s
import numpy as np

population = np.array([[1],[2],[3],[4],[5],[2],[7],[8]])
fitness = np.array([1,2,3,4,5,2,7,8])

print (s.tournament(population, fitness, 4, 1, 3))

[[ 3.]
 [ 8.]
 [ 5.]]


In [4]:
# Test crossovers
import crossovers as c
import numpy as np

a = [1,3,2,4, 5,8,7,6]
b = [3,1,5,6, 2,8,4,7]
x = np.array([a,b])

print "Initial samples", x
print "One point x-over", c.one_point(x.copy(), 1)
print "One point x-over parents are permutations", c.one_point_permutation(x.copy(), 1)
print "Two point x-over", c.two_point(x.copy(),1)

Initial samples [[1 3 2 4 5 8 7 6]
 [3 1 5 6 2 8 4 7]]
One point x-over [[1 3 2 4 5 8 4 7]
 [3 1 5 6 2 8 7 6]]
One point x-over parents are permutations [[1 3 5 6 2 8 4 7]
 [3 1 5 6 2 8 4 7]]
Two point x-over [[1 3 5 6 2 8 7 6]
 [3 1 2 4 5 8 4 7]]
