In [1]:
import selections as s
import numpy as np

population = np.array([[1],[2],[3],[4],[5],[2],[7],[8]])
fitness = np.array([1,2,3,4,5,2,7,8])

print (s.tournament(population, fitness, 4, 1, 3))

(array([[7],
       [8],
       [2],
       [1]]), array([7, 8, 2, 1]))
(array([[2],
       [1],
       [5],
       [4]]), array([2, 1, 5, 4]))
(array([[7],
       [3],
       [5],
       [2]]), array([7, 3, 5, 2]))
[ 8.  5.  7.]


In [2]:
import crossovers as c
a = [1,3,2,4, 5,8,7,6]
b = [3,1,5,6, 2,8,4,7]
x = np.array([a,b])
c.simple_permutation(x)


4


array([[1, 3, 2, 4, 8, 7, 5, 6],
       [3, 1, 5, 6, 8, 7, 2, 4]])